### ISSUE TITLE
Hello NDFour, 感谢你的爬虫

### ISSUE THREAD

**Issue by JIACHENG135** [NDFour/Book_spider#1]
我用你的爬虫爬取了偶书的数据，做了个桌面App，详情在[这里](https://www.bilibili.com/video/BV1b7411S7Na/) ～我能邀请你加入开发者列表吗？目前仓库还没公开，有两个开发者～我会在App介绍里公布数据来源和代码贡献！再次感谢

**Comment by NDFour** [comment]
很高兴我写的代码可以给你带来用处，程序是本人即兴所为。自认为程序写的很乱，所以加入开发者列表就算了。

**Comment by JIACHENG135** [comment]
哈哈哈，没有，比我写的好多啦，我现在在爬52book的数据，一共7000+页，我只爬了200多页（大概3个小时），速度有点慢诶，请问您有爬好的52book 的 csv吗 - 。-

**Comment by NDFour** [comment]
我只爬了一些测试数据，不比你的多。可以考虑放在服务区上运行。

**Comment by JIACHENG135** [comment]
好滴～
